-- CUSTOMERS
INSERT INTO CUSTOMERS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_CUSTOMER_IDS.nextVal, 'John', 'Doe', NOW(), NOW())
INSERT INTO CUSTOMERS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_CUSTOMER_IDS.nextVal, 'Max', 'Mustermann', NOW(), NOW())
-- STYLISTS
INSERT INTO STYLISTS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_STYLIST_IDS.nextVal, 'Calvin', 'Klein', NOW(), NOW())
INSERT INTO STYLISTS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_STYLIST_IDS.nextVal, 'Tommy', 'Hilfiger', NOW(), NOW())
-- TIME_SLOTS