-- CUSTOMERS
INSERT INTO CUSTOMERS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_CUSTOMER_IDS.nextVal, 'John', 'Doe', NOW(), NOW())
INSERT INTO CUSTOMERS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_CUSTOMER_IDS.nextVal, 'Max', 'Mustermann', NOW(), NOW())
-- STYLISTS
INSERT INTO STYLISTS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_STYLIST_IDS.nextVal, 'Calvin', 'Klein', NOW(), NOW())
INSERT INTO STYLISTS(ID, FIRSTNAME, LASTNAME, CREATED, UPDATED) VALUES(SEQ_STYLIST_IDS.nextVal, 'Tommy', 'Hilfiger', NOW(), NOW())
-- TIME_SLOTS
INSERT INTO TIME_SLOTS(ID, DAY, AVAILABILITY, CREATED, UPDATED) VALUES(SEQ_TIMESLOT_IDS.nextVal, PARSEDATETIME('2018-10-29', 'yyyy-MM-dd'), '0000000000000000', NOW(), NOW())